### ISSUE TITLE
Invalid property path when projectName or procedureName contains space

### ISSUE THREAD

**Issue by g-zeng** [electriccommunity/HTMLParameterPanel#5]
Paths to properties are incorrectly constructed when there is a space in projectName or procedureName.

Example:

Running with project name Training and procedure name HTML Plugin produces the following output:

Loading, please wait... 
Server Error Response:
Request Id  2
Code    NoSuchProject
Message Invalid property path: Evaluating property '/projects/Training%20Plugin/procedures/HTML%20Plugin/ec_parameterHTML' in global context Project 'Training%20Plugin' does not exist Evaluation failed
Details Evaluating property '/projects/Training%20Plugin/procedures/HTML%20Plugin/ec_parameterHTML' in global context
Project 'Training%20Plugin' does not exist
Evaluation failed

**Comment by lrochette** [comment]
The issue was due to the fact the project and procedure names are extracted from the URL but they were not "decoded" so some of the characters were replaced by their "%xx" (URL encoding) but never returned to their original format

So now spaces, dots, equal signs and more are accepted. There may be some cases left as the decode seems to have some issues with some characters. For example %3D was not decoded into an equal sign '='. Not sure how many of those cases exist.

Fixed in version 1.0.3
